version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=<your_dbname>
      - POSTGRES_USER=<your_user>
      - POSTGRES_PASSWORD=<your_pass>
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432

  server:
    build:
      context: server/
    depends_on:
      - db
    command: npm run-script start
    env_file:
      - .env
    ports:
      - 3001:3001

  client:
    build:
      context: client/
    command: npm run-script start
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  postgres_data:
